#pragma config(Sensor, in1,    PotenR,         sensorPotentiometer)
#pragma config(Sensor, in2,    PotenB,         sensorPotentiometer)
#pragma config(Sensor, dgtl2,  UltS1,          sensorSONAR_cm)
#pragma config(Sensor, dgtl4,  UltS2,          sensorSONAR_cm)
#pragma config(Sensor, dgtl6,  UltS3,          sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  EncoR1,         sensorQuadEncoder)
#pragma config(Sensor, dgtl10, EncoL1,         sensorQuadEncoder)
#pragma config(Motor,  port1,           LeftWheel2,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           Shoulder1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Shoulder2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Elbow,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RightWheel2,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//PRE-AUTON******************************************************************************************************************************************************************
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}
//my functions+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

void turn90right ()
{
	SensorValue[EncoR1] = 0;

	while(SensorValue(EncoR1) < 250)
	{
		motor[RightWheel2] = -90;
		motor[LeftWheel2] = 90;
	}
	motor[RightWheel2] = 0;
	motor[LeftWheel2] = 0;
}

void turn90left ()
{
	SensorValue[EncoL1] = 0;

	while(SensorValue(EncoL1) > -210)
	{

		motor[RightWheel2] = 90;
		motor[LeftWheel2] = -90;
	}
	motor[RightWheel2] = 0;
	motor[LeftWheel2] = 0;

}
void moveforwardRotations (float howMany)
{
	SensorValue[EncoL1] = 0;

	while(SensorValue(EncoL1) < howMany)
	{

		motor[RightWheel2] = 127;
		motor[LeftWheel2] = 127;
	}
	motor[RightWheel2] = 0;
	motor[LeftWheel2] = 0;

}
void movebackwardRotations (float howMany)
{
	SensorValue[EncoR1] = 0;

	while(SensorValue(EncoR1) < howMany)
	{

		motor[RightWheel2] = 90;
		motor[LeftWheel2] = 90;
	}
	motor[RightWheel2] = 0;
	motor[LeftWheel2] = 0;

}
void moveforward (int cm)
{
		while(SensorValue[UltS1] > cm)
	{
		motor[RightWheel2] = 63;
		motor[LeftWheel2] = 63;
	}
	motor[RightWheel2] = 0;
	motor[LeftWheel2] = 0;
}

void movebackward (int cm)
{
	while(SensorValue[UltS1] > cm)
	{
		motor[RightWheel2] = -63;
		motor[LeftWheel2] = -63;
	}
	motor[RightWheel2] = 0;
	motor[LeftWheel2] = 0;
}

void flipstar ()
{
	while(SensorValue[PotenR] < 3880)
	{
		motor[Shoulder1] = 150;
		motor[Shoulder2] = 150;
		motor[Elbow] = 0;
	}
	motor[Shoulder1] = 0;
	motor[Shoulder2] = 0;
	motor[RightWheel2] = 50;
	motor[LeftWheel2] = 50;
	wait1Msec(100);
	motor[RightWheel2] = 0;
	motor[LeftWheel2] = 0;

	while(SensorValue[PotenB] < 4095)
	{
		motor[Elbow] = -90;
	}
	motor[Elbow] = 0;

	while(SensorValue[PotenB] > 4095)
	{
		motor[Elbow] = 90;
	}
	motor[Elbow] = 0;
}

/*void raisearm ()
{
	while(SensorValue[PotenR] < 4000)
	{
		motor[Shoulder1] = 150;
		motor[Shoulder2] = 150;
		motor[Elbow] = 0;
	}
	motor[Shoulder1] = 0;
	motor[Shoulder2] = 0;

	while(SensorValue[PotenR] > 4000)
	{
		motor[Shoulder1] = -150;
		motor[Shoulder2] = -150;
		motor[Elbow] = 0;
	}
	motor[Shoulder1] = 0;
	motor[Shoulder2] = 0;

	while(SensorValue[PotenB] < 4095)
	{
		motor[Elbow] = 90;
	}
	motor[Elbow] = 0;

	while(SensorValue[PotenB] > 4095)
	{
		motor[Elbow] = -90;
	}
	motor[Elbow] = 0;
}*/


void normalize ()
{
	while(SensorValue[PotenR] > 3444)
	{
		motor[Shoulder1] = 150;
		motor[Shoulder2] = 150;
		motor[Elbow] = 0;
	}
	motor[Shoulder1] = 0;
	motor[Shoulder2] = 0;

	while(SensorValue[PotenR] < 3444)
	{
		motor[Shoulder1] = -150;
		motor[Shoulder2] = -150;
		motor[Elbow] = 0;
	}
	motor[Shoulder1] = 0;
	motor[Shoulder2] = 0;

	while(SensorValue[PotenB] < 0)
	{
		motor[Elbow] = -90;
	}
	motor[Elbow] = 0;

	while(SensorValue[PotenB] > 0)
	{
		motor[Elbow] = 90;
	}
	motor[Elbow] = 0;
}


//AUTONOMOUS****************************************************************************************************************************************************************

void doAutonomous()
{
	normalize();
	movebackwardRotations(80);
	wait1Msec(1000);
	movebackwardRotations(1200);
	flipstar();

	/*moveforwardRotations(80);
	wait1Msec(1000);
	moveforwardRotations(1200);//moves forward to required distance, using Ultrasonics

	/*
	turn90right();//turns right 90 degrees
	movebackwardRotations(90);//moves backwards, ultrasonically
	turn90left();//turns left 90 degrees
	movebackward(30);
	motor[Elbow] = -127;//puts elbow down
	wait1Msec(1200);//for 1.2 seconds
	motor[Elbow] = 0;//stops elbow
	motor[Elbow] = 127;//moves elbow back up
	wait1Msec(300);//for 0.2 seconds.
	motor[Elbow] = 0;//stops elbow
	moveforwardRotations(270);//moves forward to push star undr with hand
	flipstar();//FLIPPY STAR!!!!!!!!!!!*/


	/*motor[Elbow] = -127;
	wait1Msec(1200);
	motor[Elbow] = 0;
	wait1Msec(100);
	motor[Elbow] = 127;
	wait1Msec(200);
	motor[Elbow] = 0;
	moveforward(46);//moves forward to required distance, using Ultrasonics
	moveforward(46);//not sure why this is here. Oh well, the robot works
	turn90right();//turns right 90 degrees
	movebackward(33.02);//moves backwards, ultrasonically
	turn90left();//turns left 90 degrees
	moveforward(46+40);//gets in position
	flipstar();*/

	/*raisearm();//raises arm
	moveforward(46);//moves forward to required distance, using Ultrasonics
	moveforward(46);//not sure why this is here. Oh well, the robot works
	turn90right();//turns right 90 degrees
	movebackward(33.02);//moves backwards, ultrasonically
	turn90left();//turns left 90 degrees
	moveforward(46+40);*/

/*	motor[Elbow] = -127;
	wait1Msec(1000);
	motor[Elbow] = 0;
	wait1Msec(100);
	motor[Elbow] = 127;
	wait1Msec(200);
	motor[Elbow] = 0;
	moveforward(46+40);
	flipstar();
	movebackward(46+20);
	normalize();
	/*movebackward(4);
	moveforward(46);//moves forward to required distance, using Ultrasonics
	moveforward(46);//not sure why this is here. Oh well, the robot works
	turn90right();//turns right 90 degrees
	movebackward(33.02);//moves backwards, ultrasonically
	turn90left();//turns left 90 degrees
	moveforward(46+80);//moves forward. Should push the star under
	moveforward(46+80);//not sure why this is here either. Again, it works im not changing it
	movebackward(46);//moves backward so it can prepare for elbow down. Ultrasonically.
	motor[Elbow] = -127;//puts elbow down
	wait1Msec(1200);//for 1.2 seconds
	motor[Elbow] = 0;//stops elbow
	motor[Elbow] = 127;//moves elbow back up
	wait1Msec(200);//for 0.2 seconds.
	motor[Elbow] = 0;//stops elbow
	moveforward(46+70);//moves forward to push star undr with hand
	moveforward(46+80);//moves forward more...? Dunno why this dpopped up. Oh well.
	movebackward(46);//moves backwards*/


}


task autonomous ()
{
	doAutonomous();
}

//USER CONTROL*************************************************************************************************************************************************************

task usercontrol()
{


	while (1==1)
	{



		motor[RightWheel2] = vexRT[Ch2];//drives le right wheel

	  motor[LeftWheel2] = vexRT[Ch3];//drives le left wheel

	  motor[Shoulder1] = vexRT[Ch3Xmtr2];//controls Shoulder joint
		motor[Shoulder2] = vexRT[Ch3Xmtr2];//controls Shoulder joint

	  motor[Elbow] = vexRT[Ch2Xmtr2];//controls elbow joint

	  if(vexRT[Btn5D] == 1)
	  {
	  	doAutonomous();
		}

		if(vexRT[Btn5UXmtr2] == 1)
		{
			flipstar();
		}

		if(vexRT[Btn5DXmtr2] == 1)
		{
			normalize();
		}
	}
}
