#pragma config(Sensor, dgtl1,  LimitLeElbow,   sensorTouch)
#pragma config(Sensor, dgtl2,  UltraSonic1,    sensorSONAR_cm)
#pragma config(Sensor, dgtl4,  UltraSonic2,    sensorSONAR_cm)
#pragma config(Sensor, dgtl6,  UltraSonic3,    sensorSONAR_cm)
#pragma config(Motor,  port1,           LeftWheel2,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           Shoulder1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Shoulder2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Elbow,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          RightWheel2,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//PRE-AUTON******************************************************************************************************************************************************************
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

//AUTONOMOUS****************************************************************************************************************************************************************

task autonomous ()

{
		while(SensorValue(UltraSonic1) > 20  || SensorValue(UltraSonic1) == -1)		// Loop while robot's Ultrasonic sensor is further than 20 inches away from an object
	{                                                                         // || (or) it is '-1'.  (-1 is the value returned when nothing is in it's visable range)
		motor[RightWheel2] = 63;			// Motor on port2 is run at half (63) power forward
		motor[LeftWheel2]  = 63;			// Motor on port3 is run at half (63) power forward
	}

	  while(SensorValue(UltraSonic1) < 20 || SensorValue(UltraSonic1) == -1)
	{
		motor[LeftWheel2] = 63;
		motor[RightWheel2] = 63;
	}

	  while(SensorValue(UltraSonic1) = 20 || SensorValue(UltraSonic1) == -1)
	{
		motor[LeftWheel2] = 0;
		motor[RightWheel2] = 0;
	}

		while(SensorValue(UltraSonic2) > 20  || SensorValue(UltraSonic2) == -1)		// Loop while robot's Ultrasonic sensor is further than 20 inches away from an object
	{                                                                         // || (or) it is '-1'.  (-1 is the value returned when nothing is in it's visable range)
		motor[RightWheel2] = 63;			// Motor on port2 is run at half (63) power forward
		motor[LeftWheel2]  = 63;			// Motor on port3 is run at half (63) power forward
	}

	  while(SensorValue(UltraSonic2) < 20 || SensorValue(UltraSonic2) == -1)
	{
		motor[LeftWheel2] = 63;
		motor[RightWheel2] = 63;
	}

	  while(SensorValue(UltraSonic2) = 20 || SensorValue(UltraSonic2) == -1
	{
		motor[LeftWheel2] = 0;
		motor[RightWheel2] = 0;
	}

		while(SensorValue(UltraSonic3) > 20  || SensorValue(UltraSonic3) == -1)		// Loop while robot's Ultrasonic sensor is further than 20 inches away from an object
	{                                                                         // || (or) it is '-1'.  (-1 is the value returned when nothing is in it's visable range)
		motor[RightWheel2] = 63;			// Motor on port2 is run at half (63) power forward
		motor[LeftWheel2]  = 63;			// Motor on port3 is run at half (63) power forward
	}
		while(SensorValue(UltraSonic3) < 20 || SensorValue(UltraSonic3) == -1)
	{
		motor[LeftWheel2] = 63;
		motor[RightWheel2] = 63;
	}
	  while(SensorValue(UltraSonic3) = 20 || SensorValue(UltraSonic3) == -1)
	{
		motor[LeftWheel2] = 0;
		motor[RightWheel2] = 0;
	}


	AutonomousCodePlaceholderForTesting();
}

//USER CONTROL*************************************************************************************************************************************************************

task usercontrol()
{


	while (1==1)
{



	motor[RightWheel2] = vexRT[Ch2];//drives le right wheel

  motor[LeftWheel2] = vexRT[Ch3];//drives le left wheel

  motor[Shoulder1] = vexRT[Ch3Xmtr2];//controls Shoulder joint
	motor[Shoulder2] = vexRT[Ch3Xmtr2];//controls Shoulder joint

  motor[Elbow] = vexRT[Ch2Xmtr2];//controls elbow joint

	}
}
