#pragma config(Sensor, dgtl1,  LimitLeElbow,   sensorTouch)
#pragma config(Motor,  port1,           RightWheel2,   tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           Shoulder,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           Shoulder,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Elbow,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LeftWheel2,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//PRE-AUTON******************************************************************************************************************************************************************
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

//AUTONOMOUS****************************************************************************************************************************************************************

task autonomous ()

{

	AutonomousCodePlaceholderForTesting();
}

//USER CONTROL*************************************************************************************************************************************************************

task usercontrol()
{


	while (1==1)
{

	motor[RightWheel2] = vexRT[Ch2];//drives le right wheel

  motor[LeftWheel2] = vexRT[Ch3];//drives le left wheel

  motor[Shoulder] = vexRT[Ch3Xmtr2];//controls Shoulder joint

  motor[Elbow] = vexRT[Ch2Xmtr2];//controls elbow joint

	}
}
