#pragma config(Motor,  port3,           RightWheel2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LeftWheel2,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//PRE-AUTON******************************************************************************************************************************************************************
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

//AUTONOMOUS****************************************************************************************************************************************************************

task autonomous ()

{

	AutonomousCodePlaceholderForTesting();
}

//USER CONTROL*************************************************************************************************************************************************************

task usercontrol()
{


	while (true)
{

	motor[RightWheel2] = vexRT[Ch2];

  motor[LeftWheel2] = vexRT[Ch3];

	  UserControlCodePlaceholderForTesting();
	}
}
