#pragma config(Sensor, dgtl1,  frontLeftE,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  backLeftE,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  backRightE,     sensorQuadEncoder)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Claw1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Claw2,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//moverobot(sydeways, rotate, firword/back, 0, aut or not, speed for auto)

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include"main.c"


//PRE_AUTON------------------------------------------------------------------------
void pre_auton()
{

	bStopTasksBetweenModes = true;
	SensorValue(backLeftE) = 0;
	SensorValue(backRightE) = 0;
	SensorValue(frontLeftE) = 0;
}

//AUTONOMOUS-------------------------------------------------------------------------

task autonomous()
{

	AutonomousCodePlaceholderForTesting();
}
//USERCONTROL-----------------------------------------------------------------------

task usercontrol()
{
	int BaseX1 = 0, BaseY1 = 0, BaseX2 = 0;
	int threshold = 20;
	while (true)
	{
		//Create "deadzone" for Y1/Ch3 (FORWARD/BACK)
		BaseY1 = (abs(vexRT[Ch3]) > threshold) ? (vexRT[Ch3]) : (0);
		//Create "deadzone" for X1/Ch4 (RIGHT/LEFT)
		BaseX1 = (abs(vexRT[Ch4]) > threshold) ? (vexRT[Ch4]) : (0);
		//Create "deadzone" for X2/Ch1(Rotation of robot about z axis)
		BaseX2 = (abs(vexRT[Ch1]) > threshold+10) ? (vexRT[Ch1]*2/3) : (0);
		//call robot movement function
		moverobot(BaseX1,BaseX2,BaseY1*0.8,0,0,0);

		motor[Arm1] = vexRT[Ch1Xmtr2];
		motor[Arm2] = vexRT[Ch1Xmtr2];
		motor[Claw1] = vexRT[Ch3Xmtr2];
		motor[Claw2] = vexRT[Ch3Xmtr2];
		//motor[X2Y1] = vexRT[Ch3]+vexRT[Ch4];
		//motor[X1Y1] = vexRT[Ch3]-vexRT[Ch4];
		//motor[X2Y2] = vexRT[Ch2]-vexRT[Ch1];
		//motor[X1Y2] = vexRT[Ch2]+vexRT[Ch1];



		UserControlCodePlaceholderForTesting();
	}
}
